### ISSUE TITLE
blocked at step 4 of the installation instructions

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/vallejo_watch#1]
Hi, I'm trying to install the app locally, following the instructions in README.md, and when I run this command:

`$ django-admin.py createsuperuser`

I get:

`Unknown command: 'createsuperuser'`

**Comment by andrewschneider** [comment]
https://github.com/codeforamerica/vallejo_watch/commit/408655b9fdcf5dfae2b0ea4c701c3e8e84025828 should unblock you. thanks for catching.

**Comment by tmaybe** [comment]
Thanks! I tried `python manage.py createsuperuser` instead and am now getting:

`django.db.utils.OperationalError: no such table: auth_user`

Is there some db setup or installation I need to do first?

**Comment by andrewschneider** [comment]
https://github.com/codeforamerica/vallejo_watch/commit/e55e4149f789d01502b1d340950f43b35993fab5 should do the trick for that one. thanks!

**Comment by tmaybe** [comment]
Got it running, thanks! I would recommend adding a link to:

https://developers.google.com/maps/documentation/geocoding/?csw=1#api_key

to the README, for instructions on how to get a Google Maps Geocoding API Key.
